"""The Trade Meta-Model and Strategy Optimizer architecture."""

from algo_trader.ml.artifacts import (
    ARTIFACT_FILES,
    ModelArtifactIntegrityError,
    load_trade_meta_model,
    save_trade_meta_model,
)
from algo_trader.ml.contracts import StrategyParameterEvaluator, TradeScorer
from algo_trader.ml.evaluation import (
    QUALITY_BOUNDARIES,
    MetaModelEvaluationIntegrityError,
    evaluate_trade_meta_model,
)
from algo_trader.ml.features import FeatureIntegrityError, extract_meta_features
from algo_trader.ml.meta_model import (
    ML_ARCHITECTURE_VERSION,
    SIZING_POLICY_ID,
    BootstrapTradeScorer,
    DuplicateTrainingObservationError,
    InsufficientTrainingDataError,
    TrainedTradeMetaModel,
    chronological_calibration_split,
    extract_meta_training_samples,
    recommended_notional_for_quality,
    train_trade_meta_model,
)
from algo_trader.ml.models import (
    CategoricalParameterSpec,
    FloatParameterSpec,
    IntParameterSpec,
    MetaFeatureSchema,
    MetaModelEvaluation,
    MetaModelMetadata,
    MetaModelTrainingConfig,
    MetaTrainingSample,
    MetaTrainingSource,
    OptimizationEvaluationRange,
    OptimizationTrialResult,
    OptimizationTrialState,
    QualityBucketMetrics,
    SizeBucketMetrics,
    StrategyOptimizationResult,
    StrategyOptimizerConfig,
    TrainingSourceProvenance,
)
from algo_trader.ml.optimizer import (
    OBJECTIVE_DIRECTIONS,
    STRATEGY_OPTIMIZER_VERSION,
    OptimizationIntegrityError,
    optimize_strategy_parameters,
    parameter_distance,
)

__all__ = [
    "ARTIFACT_FILES",
    "ML_ARCHITECTURE_VERSION",
    "OBJECTIVE_DIRECTIONS",
    "QUALITY_BOUNDARIES",
    "SIZING_POLICY_ID",
    "STRATEGY_OPTIMIZER_VERSION",
    "BootstrapTradeScorer",
    "CategoricalParameterSpec",
    "DuplicateTrainingObservationError",
    "FeatureIntegrityError",
    "FloatParameterSpec",
    "InsufficientTrainingDataError",
    "IntParameterSpec",
    "MetaFeatureSchema",
    "MetaModelEvaluation",
    "MetaModelEvaluationIntegrityError",
    "MetaModelMetadata",
    "MetaModelTrainingConfig",
    "MetaTrainingSample",
    "MetaTrainingSource",
    "ModelArtifactIntegrityError",
    "OptimizationEvaluationRange",
    "OptimizationIntegrityError",
    "OptimizationTrialResult",
    "OptimizationTrialState",
    "QualityBucketMetrics",
    "SizeBucketMetrics",
    "StrategyOptimizationResult",
    "StrategyOptimizerConfig",
    "StrategyParameterEvaluator",
    "TradeScorer",
    "TrainedTradeMetaModel",
    "TrainingSourceProvenance",
    "chronological_calibration_split",
    "evaluate_trade_meta_model",
    "extract_meta_features",
    "extract_meta_training_samples",
    "load_trade_meta_model",
    "optimize_strategy_parameters",
    "parameter_distance",
    "recommended_notional_for_quality",
    "save_trade_meta_model",
    "train_trade_meta_model",
]
